SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800

DEBUGGING = True
GOD_MODE = False

ENEMY_TARGET_PLAYER = False
PLAYER_TARGET_RANGE = 100

LOGO_WIDTH = 340
LOGO_HEIGHT = 250

PLAY_BUTTON_WIDTH = 300
PLAY_BUTTON_HEIGHT = 100

GAME_OVER_WIDTH = 480
GAME_OVER_HEIGHT = 128

PLAYER_WIDTH = 32
PLAYER_HEIGHT = 32
PLAYER_SPEED = 8

ENEMY_WIDTH = 16
ENEMY_HEIGHT = 16

COLLIDE_CORRECTION_VALUE = 3

game_started = 0
difficulty = 10
enemy_count = 0
enemy_spawn_tick = 1