SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
COLLIDE_CORRECTION_VALUE = 3
DEBUGGING = True
GOD_MODE = True

LOGO_WIDTH = 340
LOGO_HEIGHT = 250

PLAY_BUTTON_WIDTH = 300
PLAY_BUTTON_HEIGHT = 100

GAME_OVER_WIDTH = 480
GAME_OVER_HEIGHT = 128

PLAYER_WIDTH = 32
PLAYER_HEIGHT = 32

ENEMY_WIDTH = 16
ENEMY_HEIGHT = 16

game_started = 0
difficulty = 10
player_speed = 8
enemy_count = 0
enemy_spawn_tick = 1
enemy_target_player = False